### ISSUE TITLE
Version 0.12: Error parsing document '/': Configuration Error: Expected end of input

### ISSUE THREAD

**Issue by hmf** [planet42/Laika#103]
I upgraded the API to version 0.12.0 according to the indications in issue #102. When I run this I get the following error:

```
sdk.laikaLocal laika.parse.markup.DocumentParser$ParserError: Error parsing document '/': Configuration Error: Expected end of input
    laika.parse.markup.DocumentParser$ParserError$.apply(DocumentParser.scala:41)
    laika.io.runtime.ParserRuntime$.$anonfun$run$21(ParserRuntime.scala:95)
    cats.syntax.EitherOps$.leftMap$extension(either.scala:144)
    laika.io.runtime.ParserRuntime$.$anonfun$run$20(ParserRuntime.scala:95)
    cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:139)
```
The exception seems to be raised [here](https://github.com/planet42/Laika/blob/26f7f69e0f2415c6a3d9c4ac120c078fc8bb15a7/io/src/main/scala/laika/io/runtime/ParserRuntime.scala#L95). 

I did a few experiments to try and see what the problem is.  First I commented the following lines from the parser:

```scala
    val parser = MarkupParser
      .of(Markdown)
      //.withRawContent
      //.using(GitHubFlavor)
      .io(blocker)
      .parallel[IO]
      //.withAlternativeParser(MarkupParser.of(ReStructuredText).withRawContent)
      .build
```

The in the renderer I commented these lines:

```scala
        val renderer = Renderer
          .of(HTML)
          //.withConfig(parser.config)
          .withMessageLevel(level)
          .io(blocker)
          .parallel[IO]
          .build
```

And always got the same error. 

In terms of the input files, I first thought that the error may be due to having no markup sources in the input directory (only in the sub-directories). I therefore pointed to a directory with 3 files: 1 `.conf`and 2 `.md` files. Still get the same error. I finally provided a file path and got an expected exception (not a directory). 

Note that the  statement `parser.fromDirectory(in).parse` returns an `IO`successfully. It is only when we try and flatMap over the IO that the error occurs. 

Any ideas what I am doing wrong? Anything else I can do to diagnose this further?

TIA

**Comment by hmf** [comment]
I have done two additional experiments. The first is using the simple API shown in the manual to transform a directory. Here is the code:

```scala
    val transformer = Transformer
      .from(Markdown)
      .to(HTML)
      .using(GitHubFlavor)
      .io(blocker)
      .parallel[IO]
      .build

    val res: IO[RenderedTreeRoot[IO]] = transformer
      .fromDirectory(in)
      .toDirectory(out)
      .transform
``` 

And here I get the same error.  So I decided to test with a single file. Here is the code: 

```scala
    val transformer = Transformer
      .from(Markdown)
      .to(HTML)
      .using(GitHubFlavor)
      .io(blocker)
      //.parallel[IO]
      .sequential[IO]
      .build

    val res = transformer
      .fromFile("/home/hmf/IdeaProjects/srllab/out/sdk/mdocTargetDirectory/dest/introduction/overview.md")
      .toFile("/home/hmf/IdeaProjects/srllab/out/sdk/laikaTargetDirectory/dest/introduction/overview.html")
      .transform
    res.unsafeRunSync()
```

And this failed with: 

```
sdk.laikaLocal java.io.FileNotFoundException: /home/hmf/IdeaProjects/srllab/out/sdk/laikaTargetDirectory/dest/introduction/overview.html (No such file or directory)
```
What is interesting here is that the base directory `/home/hmf/IdeaProjects/srllab/out/sdk/laikaTargetDirectory/dest/` exists (created by Mill), but not the rest of the path. I was assuming that Laika would create the directories automatically. I assume this is also what happens in the case of providing a destination directory. 

Can the errors I am getting be due to this? Or am I way off?

TIA.

**Comment by jenshalm** [comment]
The `toFile` case is expected I think, when you create a single file it currently expects the directory to exist. It does create all necessary target directories when using `toDirectory`.

But I am confused by the `Error parsing document '/'` bit, why would it do that?

For a bit of context, Laika 0.12 moves away from using the Typesafe Config library in favor of its own HOCON parser, so it's entirely possible that there are bugs is in this completely new module, but I'm not sure where this `document '/'` comes from. Does it work when there is no config file and just markdown without configuration header?

**Comment by jenshalm** [comment]
If you have a minimal setup with 3 files somewhere public that reproduces the issue, I'd try to run it locally.

**Comment by hmf** [comment]
> The toFile case is expected I think, when you create a single file it currently expects the directory to exist. It does create all necessary target directories when using toDirectory.

Agreed. The `toFile` worked as expected. 

>  but I'm not sure where this document '/' comes from. Does it work when there is no config file and just markdown without configuration header?

I tried with and without the `Renderer.withConfig(parser.config)` but got the same result. 

> If you have a minimal setup with 3 files somewhere public that reproduces the issue, I'd try to run it locally.

I have used/tested Laika as [Mill ](https://github.com/lihaoyi/mill) modules. This may not be easy to *debug*.  I am therefore first going to set-up a test that executes Laika as an application. If I can replicate this I will place it in the repo as a separate branch and let you know. If you are in Linux, no need to install Mill.

**Comment by jenshalm** [comment]
Ok, I would not expect that the presence of Mill makes a huge difference though.

For a bit more context when narrowing it down: The error must come either from a `.conf` file or from a configuration header in a `.md` or `.rst` file, in case you are using them. These are the HOCON bits at the start of the markup file enclosed in `{%` and `%}`. It cannot originate from anywhere else.

**Comment by hmf** [comment]
My apologies, I just realized I did not read your question on the configuration file correctly. 

> Ok, I would not expect that the presence of Mill makes a huge difference though.

Running Laika as an application or a Mill module produces the same error. However I have noticed that when running as an application it takes quite a while to terminate. 

> For a bit more context when narrowing it down: The error must come either from a .conf file or from a configuration header in a .md or .rst file, in case you are using them.

The error is due to a `directory.conf` in the root of the documents. Here is the content:

```
autonumbering {
  scope: all
}

navigationOrder = [
  introduction
]
```
If we remove the autonumbering section the rendering complete with success. The minimal example can be found [here](https://gitlab.com/hmf/srllab/tree/test_laika12). To execute the test just type the following in the root of the project.

```
mill -i sdk.runMain srllab.LaikaTest
```

If you are in Linux, the correct version of Mill will be downloaded and installed. In Windows you need to install it yourself. Please note that you need the snapshot version `0.5.2-10-d7591b` or later (Cats library clash).
 
Let me know if you need anything else. 

Thanks.

**Comment by jenshalm** [comment]
Thanks a lot for narrowing it down. This is indeed a HOCON parser bug. I could reproduce it just by running the HOCON parser on its own. I created a new ticket for this, as the investigation in this ticket is not relevant for others.

As a workaround for now, so that you can move on, you can add an explicit `=` after `autonumbering`, this succeeds in my tests. If this solves your problem for now, please close this ticket and follow the new one.

This looks like a fairly significant issue so there might be a 0.12.1 before I start with 0.13. If you notice anything else, please report as soon as possible, so that it can also be included in the patch release.

**Comment by hmf** [comment]
Seems to be working correctly with  the explicit `= `. Closing. 
Thank you.
