### ISSUE TITLE
Version 0.12: Parsing directories does not copy non-markdown sources

### ISSUE THREAD

**Issue by hmf** [planet42/Laika#105]
After upgrading from 0.11.0 to 0.12.0 the non-markdown files that were in the source directories are not copied to the destination directory any more. Is their a way to copy all non-markup files to the destination directory?

TIA

**Comment by hmf** [comment]
I am using the following code to generate the output: 

```scala
  val parser = MarkupParser
    .of(Markdown)
    .withRawContent
    .using(GitHubFlavor)
    .io(blocker)
    .parallel[IO]
    .withAlternativeParser(MarkupParser.of(ReStructuredText).withRawContent)
    .build

  val renderer = Renderer
    .of(HTML)
    .withConfig(parser.config)
    .withMessageLevel(level)
     .io(blocker)
     .parallel[IO]
     .build

   val op = parser.fromDirectory(in).parse.flatMap { tree =>
    renderer.from(tree.root)
      .toDirectory(out)
       .render
  }

op.unsafeRunSync()
```
The `parser.fromDirectory(in)` only picks up the Markdown sources. 

The following works as expected: 

```scala
val transformer = Transformer
  .from(Markdown)
  .to(HTML)
  .using(GitHubFlavor)
  .withRawContent
  .io(blocker)
  .parallel[IO]
  .build

val res: IO[RenderedTreeRoot[IO]] = transformer
  .fromDirectory(in)
  .toDirectory(out)
  .transform

res.unsafeRunSync()
```

However the above does not allow parsing `ReStructuredText` at the same time. 
Is their any way we can parse  `ReStructuredText` and copy the non-markdown sources?

TIA

**Comment by jenshalm** [comment]
Yes, that's a bit of a flaw that the Transformer does not allow `withAlternativeParser`. If I remember correctly I thought about it and then discovered that it would require some rework under the hood. I  might revisit that for 0.13.

In the meantime, you need to do it explicitly (just like Laika's own plugin):

```scala
val op = parser.fromDirectory(in).parse.flatMap { tree =>
    renderer
      .from(tree.root)
      .copying(tree.staticDocuments)
      .toDirectory(out)
      .render
```

**Comment by hmf** [comment]
That solved it.  Thank you.
