### ISSUE TITLE
Customizing home link in Helium

### ISSUE THREAD

**Issue by grbinho** [planet42/Laika#172]
Hi,

First of all, thanks for the great work on this library!

I have been trying to customize the default Helium theme for my use case, but I'm running into an issue with Home logo/link.
I can't find a way to customize the link for the Home button. It always goes to `README`.
Went through the entire manual and then checked the code to eventually find it hard coded.
I might be missing something very obvious, but is there any way to customize that?

Thanks in advance!

**Comment by jenshalm** [comment]
Apologies for overlooking this ticket, it had been added in my brief OSS hiatus this winter and when I resumed working I did not notice it for a long time.

In any case the home link is now configurable in master which will become 0.18.0 in a few weeks (see the linked PR and commits).

If anyone needs to customize the theme with the current version beyond the options of the Helium config API, have a look at the documentation for creating a copy of the theme's templates: http://planet42.github.io/Laika/0.17/03-preparing-content/03-theme-settings.html#custom-templates
