### ISSUE TITLE
Transforming empty string causes endless loop

### ISSUE THREAD

**Issue by lunedis** [planet42/Laika#200]
version: 0.17.1
scala version: 2.13.1

reproduction repo: https://github.com/lunedis/laika-empty-string-bug

```scala
import laika.api.Transformer
import laika.format.{HTML, Markdown}
val transformer = Transformer.from(Markdown).to(HTML).build
println(transformer.transform(""))
```

## Expected outcome
Empty string probably?

## Actual outcome
endless loop, maxing out one CPU core.

**Comment by jenshalm** [comment]
Thanks for reporting.

That must be a regression, I remember fixing exactly this kind of bug years ago already.
