### ISSUE TITLE
Consider using `fs2-io` for `laika-io`

### ISSUE THREAD

**Issue by armanbilge** [planet42/Laika#231]
Just a suggestion :)

The `fs2-io` module provides `Files[F]` for dealing with file I/O: https://github.com/typelevel/fs2/blob/main/io/shared/src/main/scala/fs2/io/file/Files.scala

IMHO it's worth considering for two reasons:
1. I took a quick look through your sources and I think there's a few places where you should be using `Sync.blocking` instead of `Sync.delay` b/c otherwise you are running blocking I/O on the CE3 primary threadpool which can lead to starvation etc. and other sorts of problems. If it's helpful I can try and find a reference about this. If you use fs2, this is all handled correctly for you.
2. `fs2-io` actually lets you cross-compile your code to Scala.js and run on Node.js. This is interesting, if you want to make a command-line version of Laika because Node.js has _much_ faster startup time (essentially instant) than JVM.

**Comment by jenshalm** [comment]
Closing this now as superseded by #281 which is the new umbrella ticket for tracking all PRs of this migration.

Thanks for the initial nudge! It looks like this is going to be a significant improvement.
