### ISSUE TITLE
Document "dynamic" documents

### ISSUE THREAD

**Issue by sirthias** [planet42/Laika#24]
In the source there is the concept of `Dynamic` documents, which don't appear to be documented anywhere yet.

**Comment by jenshalm** [comment]
It is documented in the manual here: http://planet42.github.io/Laika/using-laika/structure.html#document-types. So I assume you mean it should be somewhere in scaladoc, too?

**Comment by sirthias** [comment]
Ah, cool, I completely missed that. Thanks for the pointer!
