### ISSUE TITLE
laikaPreview port rendering

### ISSUE THREAD

**Issue by rossabaker** [planet42/Laika#241]
On http4s/http4s#5548, we get a bad `toString` on the port

```
sbt:http4s> docs/laikaPreview
[info] Delete API dir
[info] Initializing server...
[info] Preview server started on port com.comcast.ip4s.Literals$port$@5b1a9c24. Press ctrl-D to exit.
```

**Comment by rossabaker** [comment]
Oops, this is #221. Sorry for the noise!

**Comment by jenshalm** [comment]
No problem. Only one issue left, so 0.18.1 should be out soon. I just got a little motivation slump from the noise this week. :-)
