### ISSUE TITLE
The `Browse the API.` appears to be broken

### ISSUE THREAD

**Issue by Mirandatz** [planet42/Laika#252]
The current link https://planet42.github.com/Laika/api/laika/api/
Returns 404.

**Comment by jenshalm** [comment]
I assume you mean the link in the README? The API links in the manual are working, but the one in the README is indeed a very old link. Thanks for raising it. 

I just fixed the README, if this was the only dead link you found you can close the ticket.

**Comment by jenshalm** [comment]
Closing this under the assumption that it's fixed. If there are other broken link locations, please re-open.
