### ISSUE TITLE
Add `laikaStartPreview` task

### ISSUE THREAD

**Issue by armanbilge** [planet42/Laika#259]
Or, another solution that lets us run `mdoc --watch` and `laikaPreview` simultaneously :) As proposed in https://github.com/typelevel/sbt-typelevel/pull/189.

Briefly: the idea is to define a task that starts the preview server and returns a hook `() => ()` that should be used to shutdown the server. This enables the server preview to be composed/interleaved with other long-running tasks, such as mdoc.

Following up on a couple questions from https://github.com/typelevel/sbt-typelevel/pull/189#issuecomment-1052012722:

> I'm also generally confused by the best way to create long-running tasks in sbt. When I had to evacuate to Windows for a MacBook repair I noticed I cannot use the same shortcut to stop the task (ctrl-D).

Yes, I am confused by this too. FWIW I like how you did it, and your approach seems more flexible than what mdoc does. I think instead of looking for a specific shortcut waiting `enter` seems fine. I think this is how it's currently configured in Laika (although the log message is outdated), and is also what mdoc does IIRC.

> I also often get a bunch of error messages from http4s when stopping the preview server and I'm not sure whether there is any way to prevent that.

Yes, I got those too, and they weren't pleasant :) The easy solution is to switch from the blaze server to the ember server. It is the "blessed" backend going forward (see https://github.com/http4s/http4s/discussions/4140#discussioncomment-261676) and is overall lightweight/simpler codebase/easier to maintain.

Thanks again for all your help and time, it's been really fantastic and much appreciated!

**Comment by jenshalm** [comment]
Thanks for writing this up. Something along these lines will be part of 0.19. I might think about the exact means of supporting this, but the general goal is that integrators should be able to do something in 2 or 3 lines of code as opposed to the large chunk of copy-paste you had to do.

> I think instead of looking for a specific shortcut waiting enter seems fine. I think this is how it's currently configured in Laika (although the log message is outdated)

I'm afraid I don't understand what you mean here. I still stop the server with ctrl-D. What do you mean with "waiting enter", I do not remember I configured anything like that, at least not consciously. 😄 

And thanks for the nudge towards Ember, will try that for the next release. I assume using `ServerSentEvent` is supported there, too?

**Comment by armanbilge** [comment]
> I might think about the exact means of supporting this, but the general goal is that integrators should be able to do something in 2 or 3 lines of code as opposed to the large chunk of copy-paste you had to do.

Yes, that sounds great, thanks! :)

> I'm afraid I don't understand what you mean here. I still stop the server with ctrl-D.

Hmm, sorry, maybe I misread this snippet. But when I read it looks like it waits for any input, not specifically ctrl-D.

https://github.com/planet42/Laika/blob/9022f6f37c9017f7612fa59398f246c8e8c42c3e/sbt/src/main/scala/laika/sbt/Tasks.scala#L221-L229

> I assume using `ServerSentEvent` is supported there, too?

I will double-check for you, but AFAICT this is supported as part of http4s core and is not specific to blaze. But I actually don't know anything about this :)

**Comment by jenshalm** [comment]
Ooh, I barely remember I changed that! I think I've stolen that snippet from some other plugin.
I've updated the log. Thanks for explaining my own code to me, appreciated. 😄
