### ISSUE TITLE
`renderUnversioned = false` still renders `laika/versionInfo.json`

### ISSUE THREAD

**Issue by armanbilge** [planet42/Laika#265]
To reproduce:
1. checkout https://github.com/http4s/http4s-jdk-http-client/tree/series/0.7
2. `sbt docs/tlSite`
3. find `site/target/docs/site/laika/versionInfo.json`

My understanding from https://github.com/typelevel/sbt-typelevel/issues/100#issuecomment-1022303454 is that this should not happen.
> In case of using the `renderUnversioned` flag in the intended way, `versionInfo.json` will also only ever be published by the main branch (as it is an unversioned document itself).

None of the other unversioned documents are rendered, so I assume that it's configured correctly.

Thanks!

**Comment by jenshalm** [comment]
I need to check this, it might be that this is an oversight where I temporarily included it to test the version dropdown on output with that config. But I really wonder how it's even able to slip through... :-)

**Comment by armanbilge** [comment]
No worries! :)

I noticed you added this to the 0.19.0 milestone. A patch release of 0.18 would be ideal, but if not possible can you propose any workaround?

**Comment by jenshalm** [comment]
There is no milestone at the moment for an 0.18.2 release, that doesn't mean I cannot do one if required. In the past I rarely did patch releases simply because there did not seem to be any demand for it. Regarding potential workarounds I need to first check how/why it's actually slipping through.

**Comment by armanbilge** [comment]
Thanks, whenever you have a chance to look into it!

> In the past I rarely did patch releases simply because there did not seem to be any demand for it.

Yes, sorry for all the new demands 😬 Laika's getting to be a big hit in Typelevel :) whenever possible, anything that can be fixed with a patch works really great for us, otherwise I can try to absorb any workarounds into sbt-typelevel.

On that note, if there's anything I can do to improve your build/ci infrastructure to make it easier to release patches, please please let me know! :)

**Comment by jenshalm** [comment]
> Laika's getting to be a big hit in Typelevel :)

Oh is it? Despite the fact that there are voices saying "it is not the prettiest"? (My eyes are everywhere... 😄 )

> On that note, if there's anything I can do to improve your build/ci infrastructure to make it easier to release patches, please please let me know! :)

I'm still releasing like a monkey. 😄 And I might want to keep it that way as Laika produces so many visual artefacts, some of which are notoriously difficult to test in an automated way (e.g. PDF output). Which is why I always stop half-way through a release and check various outputs, PDF, EPUB and Laika's rendered manual.

**Comment by armanbilge** [comment]
oh my 🙈 😳  well then you also know I plan to move the Cats website onto Laika, and if that's not a feather in your cap then I don't know what is! 😁 

> Which is why I always stop half-way through a release and check various outputs, PDF, EPUB and Laika's rendered manual.

I can fix this! Here's how:

If we set you up with CI release, the release doesn't go out until you push a tag. And at that point, it's re-running CI on that commit (except this time publishing), since CI already ran on that commit when you first pushed it to the branch. So, the results should be identical.

So, that means you just need to be convinced of the worthiness of that commit. During CI, we can upload the visual artifacts as [GH artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) which you can directly download and verify from the GH CI summary. Then, if you are satisfied, you can create the tag.

What do you think, would that work for you?

!{}(https://docs.github.com/assets/cb-51016/images/help/repository/passing-data-between-jobs-in-a-workflow-updated.png)
