### ISSUE TITLE
"Source for this Page" links broken on the manual site

### ISSUE THREAD

**Issue by Sailsman63** [planet42/Laika#272]
Links to "Source for this page" in the Laika manual are somewhat malformed. For example, I get the following from [this page](http://planet42.github.io/Laika/0.18/03-preparing-content/03-theme-settings.html#):

https://github.com/planet42/Laika/tree/master/docs/03-preparing-content/03-theme-settings.md

Which returns github's custom 404. Walking the source tree, the correct URL seems to be :

https://github.com/planet42/Laika/blob/master/docs/src/03-preparing-content/03-theme-settings.md

**Comment by jenshalm** [comment]
Thank you for raising this. The src sub-directory had been introduced at some later point, and the manual had not been updated for this.

**Comment by jenshalm** [comment]
Yes, that link is broken for other reasons, thanks again.

And yes, as long as this ticket is open you can add them to the list, but most likely I'll push fixes over the weekend that will auto-close this ticket. After that it's then better to open new tickets.
