### ISSUE TITLE
Unexpected behavior on custom Block directive with 2 Default attributes

### ISSUE THREAD

**Issue by sirthias** [planet42/Laika#28]
When I add this test to the `BlockDirectiveAPISpec` it fails:

```scala
    trait RequiredAndOptionalDefaultAttribute {
      val directive = Blocks.create("dir") {
        (attribute(Default) ~ attribute(Default).optional) { (a, b) ⇒
          p(s"$a, $b")
        }
      }
    }

  "The directive parser" should "parse a directive with one required default and one optional default string attribute" in {
    new RequiredAndOptionalDefaultAttribute with TemplateParser {
      val input = """aa
        |
        |@:dir foo.
        |
        |bb""".stripMargin
      Parsing (input) should produce (root(p("aa"), p("foo, None"), p("bb")))
    }
  }
```

The directive expands to `foo, Some(foo)` rather than `foo, None`.
If I add a second argument at the directive's call site the directive is not matched at all.
Is this the expected behavior?
Can I define a directive with two anonymous attributes/arguments?

**Comment by jenshalm** [comment]
I'm afraid this is expected. I've designed the unnamed attribute for simple cases and wanted to encourage the use of named arguments for multiple parameters for better legibility. The `Default` above serves as a key for the attribute, so the directive points to the same arg twice. It's documented here: http://planet42.github.io/Laika/extending-laika/directive.html#default-attributes although it probably could be even clearer about only one being allowed.

**Comment by sirthias** [comment]
Ok, no problem.
I saw that for the ReST directives there is a `whiteSpace` parameter that allows me to have a single parameter capture the whole remaining line. Does that work for Block directives as well?

**Comment by sirthias** [comment]
To give some more background: I am actually trying to build a somewhat generic `snippet` Block directive which is supposed to take 1 or more arguments. Actually, it'd be good if all arguments after the first one were named.
Am I correct in that it's currently not possible for Block directives to accept a variable number of arguments?

**Comment by jenshalm** [comment]
Parameter values with whitespace are allowed when the value is enclosed in double quotes (should work for named and default parameters). 

Parameters can be optional, but the names must be known.

For bigger snippets you can also use "named bodies" instead of parameters.

**Comment by sirthias** [comment]
Ok, thx!

**Comment by jenshalm** [comment]
There is also the fragment directive, but I'm not sure that is useful in your case: http://planet42.github.io/Laika/using-laika/templates.html#the-directive-1
