### ISSUE TITLE
Migration steps for using fs2 in laika-io module

### ISSUE THREAD

**Issue by jenshalm** [planet42/Laika#281]
This is an umbrella ticket for tracking progress of the migration which will be delivered over a series of PRs which will all be linked from here.

Original suggestion and discussion can be found here: #231

List of PRs
========

* #279 

    Both `TextInput` and `TextOutput` can be expressed in terms of `F[_]` instead of using the previous indirection with an interim model. This way subsequent steps becomes an implementation detail. There is also a small reduction in boilerplate.
    
    This is a breaking change, but it's in "public-internal" API (used by extensions or theme providers), so only very few end users will be affected.

* #280

    This is a trivial PR that merely exists to make subsequent PRs for fs2 migration easier to review without all the noise of the type signature changes. They are needed as fs2's Files type requires an Async instance.
    
    This is a breaking change in user-facing APIs, but few users will be affected, as anyone who either used Laika's parallel execution or binary output like PDF or EPUB already needed an `Async` instance.

* #282

    This is the main migration step.
    
    Adjusting `TextInput` and `TextOutput` is straightforward due to the simplification in the first step.
    
    `BinaryInput` will receive a breaking change by modelling the input as `fs2.Stream[F, Byte]`. This is also "public-internal" API with little impact on end users.

    `BinaryOutput` is the unfortunate omission here: it cannot be migrated to fs2. The reason is that the model is currently solely used for binary output formats like PDF and EPUB which require the use of Java APIs that would not know how to handle an `fs2.Pipe`. This leaves an odd inconsistency between binary input and output, but half a migration is still better than none. This also has an impact on potential, future support for Scala.js in `laika-io` which is discussed further below.

    The types `InputRuntime`, `OutputRuntime` and `CopyRuntime` in the `laika.io.runtime` package can be removed entirely. Now that fs2 is the IO runtime they are not needed and the little integration and plumbing that is required stays in the companions of the input and output model. Additional benefit is that the amount of code to maintain in `laika-io` shrinks by 200 lines of code.

    Another integration challenge is the `FopResourceResolver` for Apache FOP in the PDF renderer, which provides font, image and other resources to FOP. Here we need to convert an `fs2.Stream` back to a Java `InputStream` to implement a synchronous Java callback. This is mildly inefficient, but given that PDF has by far the slowest renderer in Laika anyway, the difference should not be noticeable.

    Final oddity is the `ContainerWriter` for EPUB output which now talks to a `ZipOutputStream` and an `fs2.Pipe` pointing to the same underlying `OutputStream` to fulfil differing integration requirements. At least in the test suites that works fine.

* #287

    This is a set of smaller changes with little impact on user-facing APIs.

    Includes an API improvement: `InputTreeBuilder.addClasspathResource` has a new `ClassLoader` parameter to ensure the functionality can be used in code not sharing the same class loader with Laika.

* #291 

    Most entry point APIs require to specify directories for input and output, but there is also `InputTreeBuilder` which can be used to freely compose inputs. The existing API should be preserved and merely receive an addition in the form of `addStream(input: fs2.Stream, mountPoint: laika.ast.Path)`.

Related Work
==========

* #290  

    This is not related to fs2 and therefore not tracked here, as the replacement will be based on Laika's own abstraction (`laika.ast.Path`). fs2 has a path abstraction, too, but using it would be less attractive here as `laika-core` does not have a dependency on fs2 and the internal APIs would be inconsistent by using two different path abstractions. This is also scheduled for inclusion in 0.19

* **Postpone support for Scala.js in `laika-io`**

    This option has been mentioned in the original request. It is, however, beyond the scope of the 0.19 roadmap. Any future consideration would require that someone opens a ticket for this and is able to generate significant interest in the community for having this module on Scala.js. 
    
    The reluctance stems from two major aspects: the additional maintenance burden by splitting implementations across three source folders with poor IDE support for running tests, error highlighting and code navigation for those modules. And secondly by the necessary disentanglement for excluding all features that cannot be easily supported for Scala.js: PDF (impossible as Apache FOP will never run on Scala.js), EPUB (difficult, requiring a zip writer compatible with Scala.js) and the HOCON module which allows to include HOCON files fetched via HTTP (would require a dependency on an HTTP client for Scala.js).

* **Migrating the file system watcher in the preview module**

    This could also be ported to the corresponding APIs provided by fs2, but I'd prefer to tackle this post 0.19, as migrating `laika-io` provides the most benefits for now.

**Comment by jenshalm** [comment]
Thanks, it appears like fs2 provides all the functionality I need, so I wouldn't have any feature request so far. But I'd definitely appreciate an additional pair of eyes for whether I am using it correctly in the main migration step here: #282.
It'll be open for 1-2 weeks approx.

**Comment by i10416** [comment]
Thank you for splitting #257 in more granular way. Actually, I felt changes in #257 were too big to introduce.  And sorry for a bit unresponsive for a while.
