### ISSUE TITLE
Laika complains about unresolved link id references, for JSON in code fence... 

### ISSUE THREAD

**Issue by Quafadas** [planet42/Laika#288]
I have this error
```
[error] (laikaSite) laika.parse.markup.DocumentParser$InvalidDocuments: One or more invalid documents:
[error] /explanation/plotTargets.md
[error] 
[error]   [147]: unresolved link id reference:  // { // "category": "a", // "amount": 5 // }, // { // "category": "b", // "amount": 8 // }, // { // "category": "c", // "amount": -1 // } // 
[error] 
[error]   //       "values": [
[error]                      ^
[error] 
[error]   [169]: unresolved link id reference:  // { // "events": "rect:mouseover", // "update": "datum" // }, // { // "events": "rect:mouseout", // "update": "{}" // } // 
[error] 
[error]   //       "on": [
[error]                  ^
[error] 
```
Which comes from this markdown file, generated by doc. As this hasn't changed since I last tried to run it,  I don't _think_ this is me... 

Could there be a regression in a recent release? 

```scala
_Three backpacks in mdfile here_
import viz.PlotTargets.printlnTarget
import viz.extensions.*

List(("A",5),("B",8),("C",-1)).plotBarChart(List())
// {
//   "$schema": "https://vega.github.io/schema/vega/v5.json",
//   "description": "A basic bar chart example, with value labels shown upon mouse hover.",
//   "width": 400,
//   "height": 200,
//   "padding": 5,
//   "data": [
//     {
//       "name": "table",
//       "values": [
//         {
//           "category": "A",
//           "amount": 5
//         },
//         {
//           "category": "B",
//           "amount": 8
//         },
//         {
//           "category": "C",
//           "amount": -1
//         }
//       ]
//     }
//   ],
//   "signals": [
//     {
//       "name": "tooltip",
//       "value": {
//         
//       },
//       "on": [
//         {
//           "events": "rect:mouseover",
//           "update": "datum"
//         },
_Three backpacks in mdfile here_
```
All details is in the CI here; 

https://github.com/Quafadas/dedav4s/runs/6394869529?check_suite_focus=true

**Comment by jenshalm** [comment]
It feels quite unlikely that there is a regression, as that would mean that a lot of users would be affected.

Assuming that there is no bug in Laika (which is at least my current assumption), this can only happen in one of two scenarios: 

a) the code block is not properly enclosed in backticks (I assume this is what you mean by `backpacks`? 🙂 ) - this can also happen if a preceding block is not properly closed.
b) you run without GitHubFlavor Markdown - in standalone Laika this needs to be enabled explicitly, but in sbt-typelevel it's on by default.

I can think of no other scenario where it would try to parse links inside JSON. I'm also unable to reproduce it just by parsing the part you posted above - all works as expected.

**Comment by Quafadas** [comment]
Hmmm. Then my apologies. It must be me, but I can't see how. 

Thankyou for writing back. And I do mean backticks. I got auto-corrected. I'll try and see if I can isolate it to your a or b. I'm sorry for the hassle.

**Comment by jenshalm** [comment]
No problem, happy to have another look if you can produce an example where the error is reproducible for me.

**Comment by jenshalm** [comment]
For narrowing it down you can also disable all link validation: https://planet42.github.io/Laika/0.18/03-preparing-content/02-navigation.html#disabling-validation (just use `Seq(Root)` to disable everything).

I don't recommend to leave this on, as link validation is generally really useful, but you would get some output this way and maybe see, by looking at the result, if something looks wrong.

**Comment by Quafadas** [comment]
Thanks for the hint, I did this and realised it isn't respecting the code fences. 

Which I managed to trace back to something to do with the theme (or it's customisation). That was a surprise, as I haven't change it, but let's roll with that. I think this isn't to do with Laika and I?ll close the issue with my thanks and apologies for your time.

**Comment by armanbilge** [comment]
Jens comment about the GitHub-flavored markdown extension jogged my memory. I did change how that was configured in v0.4.6. @Quafadas you are possibly impacted by that, and may need to enable those extensions manually.
- https://github.com/typelevel/sbt-typelevel/pull/180
