### ISSUE TITLE
Template directive body containing braces parsed incorrectly

### ISSUE THREAD

**Issue by sirthias** [planet42/Laika#29]
I just tried to insert a javascript snippet like this

```
@:if "config.production": {
    <script>
    var foo = function() { return "bar"; };
    foo();
    </script>
}
```

However, the body parser doesn't support nested braces and terminates the body already before the line containing `foo()`.

I think nested braces should be supported.

**Comment by jenshalm** [comment]
Good spot. I suspect this is easy to improve, so I assume I'll fix this over the weekend. Until then you can escape the closing braces with a backslash as a temporary workaround.
