### ISSUE TITLE
Cross building to JavaScript

### ISSUE THREAD

**Issue by mb720** [planet42/Laika#30]
Hi and thank you very much for Laika!

I was curious whether you have considered cross-building Laika to JavaScript using [Scala.js](http://www.scala-js.org/).

As I see it, Laika would be great to use at the client side since it could transform the user's text as they type it in the browser (as opposed to sending the text to the server and back).

Best,
Matthias

**Comment by jenshalm** [comment]
Sounds like a good idea. However, this is unlikely to happen very soon, as it probably needs a lot of investigation and testing in which parts of Laika actually smoothly cross-compile. I'll add it to the backlog for now.

**Comment by jenshalm** [comment]
This is a very old ticket... BUT support for Scala.js (1.0 only) has finally arrived in Laika.
It's supported for the entire `laika-core` module and is part of the 0.14.0 release which just went out.
