### ISSUE TITLE
Navigation bar doesn't reflect structure after adding `README.md`

### ISSUE THREAD

**Issue by armanbilge** [planet42/Laika#306]
I've done my best to follow the example here:
https://planet42.github.io/Laika/0.18/03-preparing-content/01-directory-structure.html#auto-generated-navigation

In here:
https://github.com/armanbilge/sandbox/tree/fb4cf6bd0ce36e731177048286839bb5654db08b

Which gets me:
<img width="527" alt="Screen Shot 2022-07-14 at 8 10 06" src="https://user-images.githubusercontent.com/3119428/179015871-7601128e-8d7b-4886-9a5a-a9d52019824c.png">

And doesn't really reflect the nesting structure.

**Comment by jenshalm** [comment]
Great timing, that navigation directive is the next thing I was looking into anyway (in terms of making it more flexible to customize). Not aware of the issue, and won't waste your time with speculations here even though I have a suspicion what is going on. I'll simply address this as part of the improvements I'll be working on in the coming weeks.

**Comment by armanbilge** [comment]
Thanks, sounds good to me! :)
