### ISSUE TITLE
A header is not recognized unless there's an empty line before it

### ISSUE THREAD

**Issue by kaharlichenko** [planet42/Laika#307]
Consider two Markdown snippets:

1. ```markdown
   # Title
   Foreword

   ## Paragraph
   ```

2. ```markdown
   # Title
   Foreword
   ## Paragraph
   ```

Both GitHub and [Commonmark](https://spec.commonmark.org/dingus/?text=%23%20Title%0AForeword%0A%23%23%20Paragraph%0A) produce the same result in both cases, and it looks like this:

<details>
  <summary>Render</summary>
  
  # Title
  Foreword
  ## Paragraph
</details>

Laika chokes on the second input and produces this instead:

<details>
  <summary>Render</summary>
  
  # Title
  Foreword  ## Paragraph
</details>

Here's a test for `laika.markdown.BlockParsersSpec` to reproduce the issue:

```scala
test("atx header - no newline is required before the header") {
  val input = """# Title
    |Foreword
    |## Paragraph
    |""".stripMargin
  run(input, Header(1, "Title"), p("Foreword"), Header(2, "Paragraph"))
}
```

**Comment by jenshalm** [comment]
Thanks for reporting! I think this has been overlooked and never reported as most people use blank lines before headers. I personally don't really like this spec detail as it makes Markdown source less legible and parsers less performant (as it requires look-aheads), but the default/base parser should be spec-compliant, so I'll address this for the next release. I think it already works for headers with underlines, so it just needs to be expanded to work with hash prefixes, too.
