### ISSUE TITLE
Helium CSS/JS is not included in HTML in strict mode

### ISSUE THREAD

**Issue by Ostrzyciel** [planet42/Laika#310]
I'm writing an application that accepts user input and then generates HTML docs from it. The HTML is then served via a web server to the users. I want to use the default Helium theme.

Because the user cannot be trusted, I have enabled the [strict mode](https://planet42.github.io/Laika/0.18/02-running-laika/03-configuration.html#strict-mode) to disable all the complex extensions in Laika. However, I have noticed that this results in HTML files that have completely empty `<head>` elements, which means no CSS and JS files are included.

Is this even a bug? I can guess why this happens, but it's still counter-intuitive. Is there any workaround I could use?

Thanks! :)

*PS: the JS and CSS files are correctly included in the output tree. It is only the HTML file that is missing references to them.*

**Comment by jenshalm** [comment]
Ah, that is a somewhat exotic scenario that I have never thought of. And improving this would be a lot of work, so even for 0.19 which is fairly close to being finished, this would be too late.

The reason is that all extensions build around the core trait `ExtensionBundle` which has a property `useInStrictMode` so that when the user switches this flag on all bundles that have the flag set to `false` get removed. The problem with the default Helium theme is that it builds all extensions with the flag set to false and it's non-trivial to change that as Helium itself uses the public user-facing theme API for composing themes. To make this smarter those APIs would need to change so that a theme author can indicate whether an extension of their theme is compatible with strict mode or not. I'm happy to consider this for a future version, but it's too late for 0.19, so won't be this year. I have added this to the backlog for now. 

I might find a quick win for 0.19 that at least sets the flag to true for all bundles that don't install parser extensions, but no promises right now, as I'm not sure how easy/feasible that is.

The only workaround for the current version I can think of is quite cumbersome: Configure a custom `ThemeProvider` that uses the Helium `ThemeProvider` but then translates the `Theme` that the latter produces by wrapping all `ExtensionBundle` instances with that flag set to true.

**Comment by Ostrzyciel** [comment]
Thanks for the quick response and the suggested workaround! I think I will try something along these lines then.

**Comment by Ostrzyciel** [comment]
After **a lot** of experimentation I have finally found a solution that I'll share here in case anyone else stumbles upon this. The solution was not to modify the bundles included with the `Theme` – that just reenabled very minor things, like heading anchors, but nothing else. What I really needed to do was to disable the strict mode, and modify some of the bundles that are included by default to remove "unsafe"-sounding features from them. So, I disabled a bunch of block and span directives, and turned off the config parser entirely (that one alone took me 3 hours to figure out, ugh).

I license the below code under the Apache License 2.0.

<details>
  <summary>Code (Scala 3)</summary>

```scala
import cats.effect.{IO, Resource}
import laika.api.builder.{OperationConfig, TransformerBuilder}
import laika.ast.MessageFilter
import laika.bundle.{ConfigProvider, ExtensionBundle, ParserBundle}
import laika.directive.{DirectiveRegistry, DirectiveSupport}
import laika.directive.std.*
import laika.factory.{MarkupFormat, RenderFormat}
import laika.helium.Helium
import laika.io.api.TreeTransformer
import laika.io.implicits.*
import laika.parse.code.SyntaxHighlighting

object LaikaUtil:
  def makeTransformer[FMT](from: MarkupFormat, to: RenderFormat[FMT]):
  Resource[IO, TreeTransformer[IO]] =
    new TransformerBuilder(from, to, safeOpConfig.withBundlesFor(from))
      .parallel[IO]
      .withTheme(Helium.defaults.build)
      .build

  val safeOpConfig = OperationConfig(
    bundles = Seq(
      NoConfigProviderExtension,
      ExtensionBundle.LaikaDefaults,
      DirectiveSupport,
      SafeStandardDirectives,
    )
  )

  object NoConfigProviderExtension extends ExtensionBundle:
    override def description = "Registers a no-op config provider"
    override def parsers = ParserBundle(
      configProvider = Some(ConfigProvider.empty)
    )


  object SafeStandardDirectives extends DirectiveRegistry:
    def blockDirectives: Seq[laika.directive.Blocks.Directive] = List(
      BreadcrumbDirectives.forBlocks,
      NavigationTreeDirectives.forBlocks,
      ImageDirectives.forBlocks,
      StandardDirectives.callout,
      StandardDirectives.todoBlock,
    )
    def linkDirectives: Seq[laika.directive.Links.Directive] = List()
    def spanDirectives: Seq[laika.directive.Spans.Directive] = List(
      ImageDirectives.forSpans,
      StandardDirectives.todoSpan,
    )
    def templateDirectives: Seq[laika.directive.Templates.Directive] = StandardDirectives.templateDirectives
```
</summary>

**Comment by jenshalm** [comment]
Ah, this is a very bespoke set of features somewhere halfway between strict and full mode. This is not how `strict` is defined  for Laika, which essentially means "nothing beyond the core spec of supported markup languages". So even after the planned improvements, you'd still need to do most of this.

The problem I discovered when you posted this was merely that in the case of Helium strict mode removes **more** things than just the parser extensions which is unnecessary and which I intend to improve for 0.19.

But congratulations for mastering all these internals, looks good! 🙂

**Comment by jenshalm** [comment]
@Ostrzyciel - just a little update on how you could simplify your logic now with version 0.19 (RC-1 is out now, the final release will follow in a few days). 

The issues with strict mode aggressively removing too many extensions is fixed. However, you still have to deal with the fact that strict mode means no directives for markup. You can reduce your setup to just this (sorry, Scala 2 syntax):

```scala
object SafeMarkupDirectives extends ExtensionBundle {

  val description: String = "Safe markup directives for strict mode"

  private val blockDirectives = List(
    BreadcrumbDirectives.forBlocks,
    NavigationTreeDirectives.forBlocks,
    ImageDirectives.forBlocks,
    StandardDirectives.callout,
    StandardDirectives.todoBlock,
  )
    
  private val spanDirectives = List(
    ImageDirectives.forSpans,
    StandardDirectives.todoSpan,
  )

  override lazy val parsers: ParserBundle = ParserBundle(
    blockParsers = Seq(BlockDirectiveParsers.blockDirective(Blocks.toMap(blockDirectives))),
    spanParsers = Seq(
      SpanDirectiveParsers.spanDirective(Spans.toMap(spanDirectives)),
      SpanDirectiveParsers.contextRef
    )
  )
    
}
```

This just adds back the block and span directives you selected and the parsers for them (which get removed by strict mode). You do no longer have to deal with template directives (they now remain with strict mode) or config headers (always disabled in strict mode). Instead you can use standard APIs, switch strict mode on and use the above extension to get back your directives (this is untested, but should work as intended):

```scala
Transformer.from(Markdown).to(HTML).strict.using(SafeMarkupDirectives).parallel[IO].build
```

**Comment by Ostrzyciel** [comment]
Thank you for your help! This will be very helpful when I upgrade to 0.19. :)
