### ISSUE TITLE
Custom font for PDF rendering

### ISSUE THREAD

**Issue by zifeo** [planet42/Laika#35]
Is there a way to define a custom font for PDF rendering so it can be used in the stylesheet?

Also if I am not mistaken, the documentation is missing the fact that the stylesheet should be named `[...].fo.css` in order to be taken into account. Is the idiomatic way of styling a document?

**Comment by jenshalm** [comment]
Custom fonts (as well as custom stemmers and other features) are currently not supported in a straightforward way. It would require to expose the creation of the Apache FOP factory which is currently a private member of the `PDF` object. 

If you need a quick hack before this is officially supported, you could copy the `PDF` object (it's not much code) into your code base and modify the factory creation. If you find a neat way to do it, feel free to suggest it as an enhancement in the core library.

Regarding the stylesheet, you are right, that info seems to be missing. I'll be adding it when I resume working on Laika.

**Comment by zifeo** [comment]
Thanks. Finally managed to use custom fonts. The easiest way would be to add an `InputStream` argument to the `PDF` class and use a custom object specifying the config. `"org.apache.pdfbox" % "fontbox" % "1.8.12"` (not `2.0.3`) is also needed for OTF fonts.

**Comment by jenshalm** [comment]
I think an InputStream is a bit too narrow as an option. I went for the original idea to offer access to the `FopFactoryBuilder` to give access to all FOP configuration options instead of designing a custom API around the FOP features one by one. The enhancement is tracked in #42, while I'm closing this ticket now.
