### ISSUE TITLE
reStructuredText option list item separated by more than 2 spaces gets wrapped in QuotedBlock

### ISSUE THREAD

**Issue by jenshalm** [planet42/Laika#39]
With exactly 2 spaces separation the description for an option list item will be a plain paragraph as expected, with more than 2 spaces the description gets wrapped a QuotedBlock which is unnecessary and undesired.

**Comment by tundratim** [comment]
@jenshalm 

Your latest changes were just integrated into the RST plugin for GitBucket by that dev.  I have just confirmed this fixes the problem I reported initially.

Many thanks!
