### ISSUE TITLE
reStructuredText: image references do not honour configuration for link validation

### ISSUE THREAD

**Issue by jenshalm** [planet42/Laika#398]
The following sample code
```scala
val transformer = Transformer
  .from(ReStructuredText)
  .to(HTML)
  .withConfigValue(LinkConfig(excludeFromValidation = Seq(Root)))
  .build
val input                       =
  """Some text
    |
    |.. image:: unresolved_Image.png
    |
    |followed by something else""".stripMargin
```

produces the following output:
```html
<p>Some text</p>
<p><code></code></p>
<p>followed by something else</p>
```

With link validation turned on, the result is the same. Both outcomes are unexpected.

This issue is specific to the reStructuredText transformer, the Markdown parser behaves as expected.

### Expected results

With link validation turned off, an image tag with the specified URL should be rendered.

With link validation turned on, the transformation should fail with an error message.

**Comment by FatConan** [comment]
I just grabbed the 0.19.1 version (adding the "org.planet42" %% "laika-core" % "0.19.1" dependency) and I'm encountering a new issue with the rendering. Using the above transformer and input and this call:
```
def main(args: Array[String]){
    transformer.transform(input).map(print)
}
```
My output is 
```
<p>Some text</p>
<p><img src="unresolved_Image.html"></p>
<p>followed by something else</p>
```

The image extension appears to have been transformed into *.html* at some point in the render.

**Comment by jenshalm** [comment]
Ah, that's unfortunately a separate issue that the original fix did not catch as I used a more narrow test case than the example you gave.

The new issue, including a temporary workaround until 0.19.2 is #408.

Just some feedback why you keep running into things like this: download stats show that 98% of users use Laika via its sbt plugin which transforms entire directories of inputs and has significantly different logic for both, link validation and path translation and therefore is not affected by those issues. Since most users are fine, these things did not get reported yet. 

Your much simpler, standalone use case uses too much of the advanced logic internally that is intended for the directory use case. For example, when transforming a single string, link validation should actually be off by default, as the validation is futile in this case: the transformer does not even have the context for performing any validation. There will be further simplifications for standalone transformers in the next version.

Sorry for the inconvenience, at least your reports will help that those use cases receive some much needed polishing and fixes.

**Comment by FatConan** [comment]
Thank you for the update. I imagine my use case isn't at all standard. I use Laika to read certain metadata from a RST template as well as rendering its content in isolation, rather than for building a complete document tree, so it's pretty esoteric.
