### ISSUE TITLE
Some http link in ReST file crashes parser

### ISSUE THREAD

**Issue by amuramatsu** [planet42/Laika#45]
When parsing ReST file which has http-link with a IP address starts with 1 or 2 digits, like as `http://10.20.30.40/` or `http://1.2.3.4/`, parser throws scala.MatchError() exception.

I tested this issue with below test code.

https://github.com/amuramatsu/Laika/blob/46436499ec352eb2310cd187fda53fa3519be084/core/src/test/scala/laika/parse/rst/InlineParsersSpec.scala#L286-L302

**Comment by jenshalm** [comment]
Thanks for narrowing it down and providing test cases that reproduce the issue, this greatly helps speeding up the fix. Although in this case I only kept one of the tests, as the difference was not in the number of digits as you suspected, but even weirder: it depended on whether the IP address contained a `.0.` or not.
