### ISSUE TITLE
escaping markup in link labels

### ISSUE THREAD

**Issue by bowerth** [planet42/Laika#60]
hello - many thanks for the tool - i'd have a suggestion for improvement:

escaping underscores with backslash only works in regular text - could this be supported within link labels? in the example below, the middle word in the link label creates an `<em>` tag in the HTML source code

```
[gtm\_bds\_test](http://google.com)

gtm\_bds\_test
```

```
<p><a href="http://google.com">gtm<em>bds</em>test</a></p>
<p>gtm_bds_test</p>
```

**Comment by jenshalm** [comment]
Sorry for the very late response. Laika always intended to properly support what you expected like almost every other Markdown parser. In turned out that it was actually a bug that it did not work.

Fixed now on master, will be part of the 0.8.0 release which will be ready in the coming weeks.
