### ISSUE TITLE
Urls with accents are not processed correctly in RestructuredText format

### ISSUE THREAD

**Issue by apps4uco** [planet42/Laika#63]
# Code 
 Transform from ReStructuredText to HTML.withMessageLevel(Warning) fromDirectory "dir" toDirectory "dir/html/"

# Input

    https://en.wikivoyage.org/wiki/Capurganá

# Result in Laika

    <p><a href="https://en.wikivoyage.org/wiki/Capurgan">https://en.wikivoyage.org/wiki/Capurgan</a>á</p>

Note the final a with an accent doesnt get included in the url

# Result in Pandoc - just to check

    <p>https://en.wikivoyage.org/wiki/Capurganá</p>

Note it doesnt get processed as a URL at all

# Expected Result

    <p><a href="https://en.wikivoyage.org/wiki/Capurganá">https://en.wikivoyage.org/wiki/Capurganá</a></p>

**Comment by jenshalm** [comment]
I'm afraid your expectation is not correct. Laika uses the corresponding RFC grammar for parsing URIs and unicode characters are not allowed in it and should be percent-encoded (e.g, %20).

For embedded URLs Laika simply stops when encountering the first non-URL character (in this case `á`). It might be better to try to implement the Pandoc behaviour instead, but that would require defining a list of accepted separator characters at the end of a URL (maybe anything that is not a character).

**Comment by jenshalm** [comment]
The Pandoc behaviour is now implemented in master.
