### ISSUE TITLE
Support Pandoc/Hakyll/Jekyll-style metadata blocks

### ISSUE THREAD

**Issue by mdekstrand** [planet42/Laika#8]
Several other tools - Jekyll, Pandoc/Hakyll, etc. - have metadata headers delimited with `---`:

```

---
title: Some Title

---
```

It'd be nice, for compatibility, if Laika could also support these. Pandoc also supports `...` s the ending delimiter for the metadata header. It's probably compatible enough to just read `Config` from them - the common usage of these fields lies in the intersection of YAML and Typesafe config syntax.

**Comment by jenshalm** [comment]
I know this is an ancient ticket...

But with the new ExtensionBundle API (part of the upcoming 0.9 release) it will be much more convenient to add new or adjust existing features.

As discussed above, I won't add a built-in option to use Hocon config with Jekyll delimiters, as that might be confusing for users and make them run into errors should they use Yaml syntax in their headers.

But if you know what you are doing, you can now explicitly customize the parsing of headers:

```
object JekyllHeaders extends ExtensionBundle {
  override lazy val parserDefinitions = ParserDefinitionBuilders(
    configHeaderParsers = Seq(ConfigHeaderParser.betweenLines("---","---"))
  )
}

val transformer = Transform.from(Markdown).to(HTML).using(JekyllHeaders)

transformer.fromFile("...").toFile("...")
```

I am closing this ticker now as the feature is fully implemented on master. However, I would not recommend to build a snapshot as the 0.9 release will see lots of API changes (getting closer to the 1.0 release), so it's better to wait for the release.
