### ISSUE TITLE
Markdown incorrect code fence output:: split and not terminating correctly

### ISSUE THREAD

**Issue by hmf** [planet42/Laika#94]
I am using the latest version o Laika with Github flavor and raw content activate. 
When I place the following code fence in a Markdown file   it splits the code fence and has the fence colons appear verbatim. The code is here:

https://gitlab.com/-/ide/project/hmf/srllab/edit/test_mill/-/sdk/docs/mdoc/dev_notes/laika_debug.md

And I get the following output:

![Screenshot from 2019-09-08 11-54-58](https://user-images.githubusercontent.com/1138178/64487255-f8bde080-d22f-11e9-9cb9-e1cb19b6e887.png)

**Comment by jenshalm** [comment]
Thanks for reporting. It's fixed in master, but if you want to use a snapshot you'd need to adjust for the (fairly significant) API changes in the upcoming version.

I'll have a look at your other tickets in the coming days.

**Comment by hmf** [comment]
@jenshalm Its not critical so I will wait for the API change to be documented because I will have to redo the [Mill](http://www.lihaoyi.com/mill/) modules. Thank you.
