### ISSUE TITLE
Incorrect rendering of code fence to HTML due to empty line

### ISSUE THREAD

**Issue by hmf** [planet42/Laika#96]
I have the following Markdown source:

```
object sdk extends MDocModule with LaikaModule {
  val appVersion = "0.1.0"
}
```

```
object sdk extends MDocModule with LaikaModule {

  val appVersion = "0.1.0"
}
```
Source can be found [here](https://gitlab.com/hmf/srllab/blob/test_mill/sdk/docs/mdoc/dev_notes/objectfence.md)

The HTML however does not produce the correct result for the second case (please see attached file [objectfence.html.txt](https://github.com/planet42/Laika/files/3648284/objectfence.html.txt), remove txt extension to view correctly). 

The only difference is the empty line after object declaration.

**Comment by jenshalm** [comment]
This looks to be a duplicate of #94 which is fixed on master?

**Comment by hmf** [comment]
Oops. Looks like it. Sorry about that.
